service:
  name: serverless-ts-boilerplate

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ../../../webpack.config.js
    includeModules: false #modules should be in layer
  usedLayers:
    layerVersion: 1
    modules: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:layer:${self:service.name}-layers-${self:provider.stage}:${self:custom.usedLayers.layerVersion}

provider:
  name: aws
  region: 'us-east-1'
  runtime: nodejs8.10
  stage: dev
  memorySize: 256
  timeout: 10
  environment:
    NODE_PATH: "./:/opt/node_modules" # new path to layered node_modules
  tags:
    environment: ${self:provider.stage}
    project: ${self:service.name}

functions:
    createChatMessage:
      handler: createChatMessage.handler
      layers:
        - ${self:custom.usedLayers.modules}
      events:
        - http:
            method: POST
            path: /messages
            private: false
    getMessage:
      handler: getMessage.handler
      layers:
        - ${self:custom.usedLayers.modules}
      events:
        - http:
            method: GET
            path: /messages
            private: false
    getRoomMessages:
      handler: handler.getRoomMessages
      layers:
        - ${self:custom.usedLayers.modules}
      events:
        - http:
            method: GET
            path: /messages/room/{room}
            private: false
    getUserMessages:
      handler: handler.getUserMessages
      layers:
        - ${self:custom.usedLayers.modules}
      events:
        - http:
            method: GET
            path: /messages/user/{userId}
            private: false