service:
  name: serverless-ts-boilerplate-layers

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev #choose stage to deploy

layers:
  layerNode:
    name: ${self:service.name}-${self:provider.stage}
    path: layer_node-${self:provider.stage}
    description: All required by ${self:provider.stage} project node modules
    compatibleRuntimes:
      - nodejs8.10