const HEADERS_NAMES = {
    ACCESS_CONTROL_ALLOW_ORIGIN: 'Access-Control-Allow-Origin',
    ACCESS_CONTROL_ALLOW_CREDENTIALS: 'Access-Control-Allow-Credentials',
    CACHE_CONTROL: 'Cache-Control',
    CONTENT_TYPE: 'Content-Type'
}

const ACCESS_CONTROL_ALLOW_ORIGIN_TYPES = {
    ALLOW_ALL: '*'
}

const CACHE_CONTROL_TYPES = {
    NO_STORE: 'no-store',
    NO_CACHE: 'no-cache'
}

const CONTENT_TYPE_TYPES = {
    APPLICATION_JSON: 'application/json',
    TEXT_PLAIN: 'text/plain'
}

const DEFAULT_CORS_HEADERS = {
    [HEADERS_NAMES.ACCESS_CONTROL_ALLOW_ORIGIN]: ACCESS_CONTROL_ALLOW_ORIGIN_TYPES.ALLOW_ALL,
    [HEADERS_NAMES.ACCESS_CONTROL_ALLOW_CREDENTIALS]: true
}

const NO_CACHE_CORS_HEADERS = {
    ...DEFAULT_CORS_HEADERS,
    [HEADERS_NAMES.CACHE_CONTROL]: `${CACHE_CONTROL_TYPES.NO_CACHE}, ${CACHE_CONTROL_TYPES.NO_STORE}`
}

export const headers = {
    HEADERS_NAMES,
    CONTENT_TYPE_TYPES,
    DEFAULT_CORS_HEADERS,
    NO_CACHE_CORS_HEADERS
}
